require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.3
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - vendor/ruby/**/*
    - node_modules/**/*
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - db/migrate/*
    - config/environments/*
    - lib/tasks/**/*
    - spec/**/*
    - features/**/*
    - app/**/*
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 1000
